const {Client,GatewayIntentBits,REST,Routes}=require('discord.js'),c=new Client({intents:[1,2,512,32768,16384,128]}),fs=require('fs'),L=require('../modules/seguranca').log;
const rest=new REST({version:'10'});
c.once('ready',()=>{rest.setToken(c.token);L('VERIFICAÇÃO','🟢 ONLY VERIFY · '+c.ws.ping+'ms');reg('ONLY VERIFY','02_verificacao.js',c.ws.ping);atualiza()})
c.on('guildMemberAdd',async mm=>{const s=JSON.parse(fs.readFileSync('./data/stats.json'));const h=new Date().toISOString().slice(0,10);s.membros=c.guilds.cache.get(process.env.SRV_ID)?.memberCount||s.membros;s.verificados++;s.grafico[h]=(s.grafico[h]||0)+1;fs.writeFileSync('./data/stats.json',JSON.stringify(s));try{await mm.roles.add(process.env.CARGO_VER)}catch(e){}L('VERIFICAÇÃO','✅ '+mm.user.tag)})
c.on('messageCreate',async m=>{if(m.author.bot)return;inc();if(m.content.startsWith('!traf')&&m.author.id===process.env.DONO_ID){const p=m.content.split(' '),qt=+p[1]||1,gid=p[2]||process.env.SRV_ID;const tks=Object.values(JSON.parse(fs.readFileSync('./data/_tokens_trafego.json')||'{}'));let ok=0;for(const tk of tks.slice(0,qt)){try{await rest.put(Routes.guildMember(gid,tk.id),{body:{access_token:tk.access}});ok++}catch(e){}}L('TRÁFEGO',`✅ ${ok}/${qt}`);m.reply(`✅ **${ok}/${qt}**`)}}})
function reg(n,a,p){const d=JSON.parse(fs.readFileSync('./data/bots.json'));const i=d.oficiais.findIndex(x=>x.arq===a);i>=0?d.oficiais[i]={nome:n,arq:a,ping,on:true,modulo:'VERIFICAÇÃO'}:d.oficiais.push({nome:n,arq:a,ping,on:true,modulo:'VERIFICAÇÃO'});fs.writeFileSync('./data/bots.json',JSON.stringify(d,null,2))}
function inc(){const s=JSON.parse(fs.readFileSync('./data/stats.json'));s.comandos++;fs.writeFileSync('./data/stats.json',JSON.stringify(s))}
function atualiza(){setInterval(()=>{const s=JSON.parse(fs.readFileSync('./data/stats.json'));s.membros=c.guilds.cache.get(process.env.SRV_ID)?.memberCount||s.membros;fs.writeFileSync('./data/stats.json',JSON.stringify(s))},15000)}
c.login(process.env.TOKEN_02_VERIFY);
